import type { Metadata } from 'next';
import '@/styles/globals.css';
import Link from 'next/link';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html>
      <body>
        <div className='navbar'>
          <Link href="/">Home</Link>
          <Link href="/list">list 페이지</Link>
        </div>
        {children}
        </body>
    </html>
  );
}
