import type { Metadata } from "next";
import "@/styles/globals.css";
import AuthProvider from "@/containers/auth/AuthProvider";
import { getRefreshTokenCookie } from "./action";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

interface RootLayoutProps {
  landing: React.ReactNode;
  children: React.ReactNode;
}
export default async function RootLayout({
  landing,
  children,

}: RootLayoutProps) {
  // const refreshToken = await getRefreshTokenCookie();
  return (
    <html>
      <body>
        <div className="">
          <AuthProvider landing={landing}
            // refreshTokenCookie={refreshToken}
          >
            {children}
          </AuthProvider>
        </div>
      </body>
    </html>
  );
}